name: Response Time CI
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  response-time:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: response-time
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
